# Generated by Django 2.1.1 on 2018-09-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_auto_20180923_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
